docker stack rm letschat
docker stack rm django
docker stack rm counter
docker stack rm wordpressi
docker service rm weather
docker service rm redis
docker service rm db
docker service rm result
docker service rm vote
docker service rm worker
docker service rm uber
docker service rm instagram
docker service rm twitter
