version: '3.1'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: /run/secrets/mysql_user
       MYSQL_PASSWORD: /run/secrets/mysql_password

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: /run/secrets/wordpress_db_user
       WORDPRESS_DB_PASSWORD: /run/secrets/wordpress_db_password
volumes:
    db_data:

secrets: 
    mysql_root_password:
        external: true
    mysql_user:
        external: true
    mysql_password:
        external: true
    wordpress_db_user:
        external: true
    wordpress_db_password: 
        external: true 
