version: "3"

services:
  nginx:
    image: aslaen/nginx_lchat
    depends_on:
      - chatapp
    ports:
      - 85:80

  chatapp:
    image: sdelements/lets-chat
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
