version: '3'
services:
  prom:
    image: lindison/prom:laptop
    ports:
     - "9090:9090"
    deploy:
      placement:
         constraints:
           - node.role == manager
  grafana:
    image: grafana/grafana
    ports:
     - "3000:3000"
    deploy:
      placement:
         constraints:
           - node.role == manager
