# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
(1..3).each do |i|
  config.vm.define "node-#{i}" do |node|
    node.vm.box = "lindison/alpine-3.5.1_x86-64"
    node.vm.hostname = "node-#{i}"
    node.vm.network "private_network", ip: "192.168.50.5#{i}"
#    node.vm.network "public_network", bridge: "en11: USB3.0 Dual Video Dock", ip: "192.168.1.5#{i}"
    node.vm.synced_folder ".", "/vagrant", disabled: true
    node.vm.provision :shell, path: "bootstrp-docker.sh"
    node.vm.provision :shell, path: "setup_profile.sh"
  end
end
end
